Feat/adding permissions for adding households
commit-crimes/shelf-life pull request #214
Opened 2024-11-22 15:58 UTC by Dearop

2024-11-27 16:58 UTC, AleMerRom requested changes
# PR Review

## Description
In this PR, you have added a layer into the invitation. These changes have affected viewModels, UI files and tests. 

## What's new

### Functionality

1. **Invitation.kt**:
You have created a new dataclass for the invitation.

2. **InvitationRepository.kt**:
you have added an interface for the InvitationRepository. In it you have created the following functions:
   - declineInvitation
   - acceptInvitation
   - getInvitations
   - sendInvitations
 
3. **InvitationRepositoryFirestore.kt**:
In this file, you override the function inside the previous interface and connect it to the firebase. 
You have also created a private function, convertToInvitation. This functions convert Firestore document into an Invitation object. You use this function inside the getInvitations function.

4. **InvitationViewModel.kt**:
You use a firestore listener which is a necessary component. But currently it only listens every time you sign in. This means if you are invited to a household whilst you have the app open, it will not appear. You might have to add the listener somewhere else. 
You have also added the following functions:
   - loadInvitations
   - sendInvitation
   - acceptInvitation
   - declineInvitation

5. **InvitationScreen.kt**:
You have added a invitation screen into our app. This screen is used to invite other users. In it you can add a new user and eliminate others. 

6. **NavigationActions.kt** & **MainActivity.kt**:
Here you make the necessary updates to accommodate the invitation screen
Inside **NavigationActions.kt**, you have created a Route and a Screen called FIRST_TIME_USER, but are never used anywhere. 

7. **FirstTimeWelcome.kt**:
In this file, you have added a log out button in the FirstTimeWelcomeScreen. The functionality works perfectly. The only issue is that the button is way to big, and it looks weird.

8. **ProfileScreen.kt**:
You have added a list of all non-resolved invitations inside the ProfileScreen. When I tested this on my phone it did not appear on the second phone. 

9. **for the rest of non-test files**:
In some you have updated the code to the changes to have made in the previous classes. In some other, you have changed the name of some variables to be more representative.

10. **Testing Files**
You have updated the name of the functions that are used, and changed the mocking. You have also put some tests in comments. I have spoken with you and know that you will correct these tests when we change the whole ViewModel in the near future.

---

**Code Quality**

All the code looks very nice. You have changed some names of variables that improves it. But you have some fully commented out tests. In this situation there is not much you can do, but it is not a good practice. 

--- 

**Testing**

You have updated the UI tests so that they work. But as you have said, there are currently no test for the ViewModel side, these will be added when the refactoring of the backend is completed.

## Recomended Changes
1. Make the listerner be always active. See point 4.
2. Change the size of the button in the **InvitationScreen.kt**
3. When testing this on my phone, I have encountered a few problems.
i. The list of unresolved invitation does not appear, it was accepted directly. 
ii. it then would no longer appear on the original phone. (When I tested it again, but in the other direction, it did work)

Overall good work

2024-11-27 16:58 UTC, AleMerRom commented on app/src/main/java/com/android/shelfLife/model/household/HouseHoldRepository.kt
> +  fun getUserIds(users: Set<String?>, callback: (Map<String, String>) -> Unit)
I like that you have changed the list to a Set which means there will not be any deduplication of users in the list of users

2024-11-27 17:06 UTC, Dearop commented
The reason why the features weren't working properly is because you merged in code from main and then ran it on your phone without checking if it compiled because after your merge the code no longer compiled.

2024-11-28 23:54 UTC, AleMerRom reviewed
You have made the changes that were needed. 

We worked together to find the errors in your implementation. You have corrected them all. The listeners have been added. This means the profile screen updates nicely to the invitations (when household created or later on).

Good job

2024-11-28 23:54 UTC, AleMerRom commented on app/src/main/java/com/android/shelfLife/model/creationScreen/CreationScreenViewModel.kt
> +class CreationScreenViewModel(initialEmails: Set<String> = emptySet()) : ViewModel() {
I like that you are now using a more representative name

2024-11-28 23:54 UTC, AleMerRom commented on app/src/main/java/com/android/shelfLife/model/household/HouseholdViewModel.kt
> +    private val houseHoldRepository: HouseHoldRepository,
I like the new name

2024-11-28 23:54 UTC, AleMerRom commented on app/src/main/java/com/android/shelfLife/model/household/HouseholdViewModel.kt
> +  /**
It would be nice if you did not leave commented out code

2024-11-28 23:54 UTC, AleMerRom commented on app/src/main/java/com/android/shelfLife/model/invitations/InvitationRepository.kt
> +  fun addInvitationListener(onUpdate: (List<Invitation>) -> Unit, onError: (Exception) -> Unit)
You have now added listener that constantly check

2024-11-28 23:54 UTC, AleMerRom commented on app/src/main/java/com/android/shelfLife/model/invitations/InvitationViewModel.kt
> +        startListeningForInvitations()
Previously you only listened when the app was opened. Now with this it will constantly listen.

2024-11-28 23:54 UTC, AleMerRom commented on app/src/main/java/com/android/shelfLife/model/invitations/InvitationRepositoryFirestore.kt
> +  override fun addInvitationListener(
You have added the function for a constant listen. Thanks

2024-11-28 23:55 UTC, AleMerRom approved these changes
I have misclicked, check last message for review.

2024-11-28 23:55 UTC, merged