Feat/add food and household models
commit-crimes/shelf-life pull request #232
Opened 2024-11-28 22:24 UTC by ricardo-perello

### **Pull Request Description:**

This PR introduces the implementation of models and repositories for handling **Households** and **FoodItems** in the Shelf Life application. The key features include:

---

#### **Key Additions:**

1. **Household Model:**
   - Data class `HouseHold` with properties:
     - `uid`: Unique identifier for the household.
     - `name`: Name of the household.
     - `members`: List of member IDs.
     - `sharedRecipes`: List of shared recipe IDs.
   - Repository Interface (`HouseHoldRepository`) and Firestore implementation (`HouseholdRepositoryFirestore`) to manage CRUD operations and local caching for households.

2. **FoodItem Model:**
   - Data class `FoodItem` with properties:
     - `uid`: Unique identifier for the food item.
     - `foodFacts`: General information about the food product.
     - `buyDate`, `expiryDate`, `openDate`: Dates related to the food item.
     - `location`: Storage location (e.g., fridge, pantry).
     - `status`: Current status of the food item (e.g., opened, consumed).
     - `owner`: User ID of the item's owner.
   - Repository Interface (`FoodItemRepository`) and Firestore implementation (`FoodItemRepositoryFirestore`) to manage CRUD operations and real-time syncing with Firestore.

3. **Local Cache:**
   - Implemented `MutableStateFlow` for local caching in both repositories (`HouseHold` and `FoodItem`), ensuring the app can access the latest data without waiting for Firestore latency.

---

#### **Tests:**
- Added comprehensive unit tests for:
  - Household repository CRUD operations and cache syncing.
  - Food item repository CRUD operations, real-time listener updates, and cache syncing.
  - User repository integrations with households and recipes.

---

#### **Improvements to Overall Architecture:**
- Refactored data flow to decouple models and repositories, promoting scalability.
- Ensured better integration with other app components through state flows and repository patterns.

---

### **Reviewer Notes:**
- This PR doesn't finalize all model-related implementations but lays the groundwork for further development.
- The changes include tests for existing functionality and can be merged to the `main` branch without blocking additional work on the `fix/221-create-models` branch.

---

### **How to Test:**
1. Check out the branch.
2. Run unit tests for all repositories:
   ```bash
   ./gradlew testDebugUnitTest
   ```
3. Review the new repository structure and confirm the integration of the local cache mechanism.

---

**Link to related issues:**
Closes #183 (if applicable).

2024-11-28 22:52 UTC, ricardo-perello commented
i have 72% and 76% coverage according to jacoco

2024-11-29 09:31 UTC, matvitn requested changes
Really good PR overall!!!! The code looks really clean and its really motivating to see the architecture we have been planning coming together like this!

The tests look really good and the interaction with Firebase seems very efficient in most parts! The new way of searching for households and getting the fooditem lists will create a noticeable efficiency improvement in the app and I'm looking forward to seeing it used together with the UI screens.

Despite the really good code there are 2 things that I would like you to change:
 1) deleting household and fooditem in the model is done with a filter which is less efficient than simply using the delete function (O(n) vs O(1) approximately)
 2) Changing the ENUM name from CLOSED to UNOPENED might lead to compatibility issues and I find CLOSED to be better for UX then UNOPENED (CLOSED is simpler and more straightforward)

On top of that there are a few things that I don't think need to be changed for this PR but should be taken into account for the future:
- you don't have enough coverage for the new code. This is to be expected due to the skeleton classes and the interface but its something we should definitely improve in the future
- you set the default location of fooditem to OTHER instead of PANTRY like we had before. I definitely think this is an improvement but we need to be careful about this change for future compatibility with tests and other code


Overall this was a really good PR that introduced the new models with much better architecture!!! Thank you for your contribution and let me know when the changes are made so I can approve this really good PR!!!

2024-11-29 09:31 UTC, matvitn commented on app/src/main/java/com/android/shelfLife/model/newFoodItem/FoodItem.kt
> +  UNOPENED,
for compatibility with tests it would be better to have the status "CLOSED" instead of "UNOPENED" as the tests use closed

2024-11-29 09:31 UTC, matvitn commented on app/src/main/java/com/android/shelfLife/model/newFoodItem/FoodItemExtensions.kt
> +  val location = locationStr?.let { FoodStorageLocation.valueOf(it) } ?: FoodStorageLocation.OTHER
this is something we have to check as to how it will affect other parts of the project (like tests) since the old food items classes take PANTRY as the default location (and your version takes OTHER). I think OTHER makes much more sense but I'm still letting you know since other parts of the project might behave differently and cause bugs if we're not careful

2024-11-29 09:31 UTC, matvitn commented on app/src/main/java/com/android/shelfLife/model/newFoodItem/FoodItemRepositoryFirestore.kt
> +        currentFoodItems.add(foodItem)
Doing it like this might cause the issue we talked about before with two people separately editing the same food item and leading to only the last update being taken into account. Since this is mainly a problem related to the amount field we should maybe create a separate method for that in the future

2024-11-29 09:31 UTC, matvitn commented on app/src/main/java/com/android/shelfLife/model/newFoodItem/FoodItemRepositoryFirestore.kt
> +      val currentFoodItems = _foodItems.value.filterNot { it.uid == foodItemId }
Im almost 100% sure theres a delete function that takes a UID (or even the whole item) and deletes it in O(1). Doing a filter deletes it in O(n) so it might be good to change that

2024-11-29 09:31 UTC, matvitn commented on app/src/main/java/com/android/shelfLife/model/newFoodItem/FoodItemRepositoryFirestore.kt
> +  fun stopListeningForFoodItems() {
Very good idea, we can use this when we move to another screen and ensure that for every navigation to the overview screen, we fetch the food items. That way we only need to be actively listening to the firebase for foodItems when we are on the overview screen

2024-11-29 09:31 UTC, matvitn commented on app/src/main/java/com/android/shelfLife/model/newhousehold/HouseHoldRepositoryFirestore.kt
> +  suspend fun initializeHouseholds(householdIds: List<String>) {
Why is this function not present in the interface? Normally you'd have it defined in the interface and the override it here.

2024-11-29 09:31 UTC, matvitn commented on app/src/main/java/com/android/shelfLife/model/newhousehold/HouseHoldRepositoryFirestore.kt
> +      val currentHouseholds = _households.value.toMutableList()
Why do you convert it to a MutableList? wouldn't it be better to have a type for the variable that doesn't require such a conversion?

2024-11-29 09:31 UTC, matvitn commented on app/src/main/java/com/android/shelfLife/model/newhousehold/HouseHoldRepositoryFirestore.kt
> +      val currentHouseholds = _households.value.filterNot { it.uid == id }
Same feedback that I gave in FoodItem model. Im pretty sure there exists a delete function that does it in O(1)

2024-11-29 09:31 UTC, matvitn commented on app/src/main/java/com/android/shelfLife/utilities/FoodFactsExtensions.kt
> +fun FoodFacts.toMap(): Map<String, Any?> {
Very good idea!!! this will make the code much cleaner through the reuse of these functions. The only thing is that id call the class FoodFactsUtils (😂👍)

2024-11-29 09:31 UTC, matvitn commented on app/src/main/java/com/android/shelfLife/viewmodel/HouseholdViewModel.kt
> +class HouseholdViewModel(private val repository: HouseHoldRepository) : ViewModel() {
good skeleton for the new view model. just make sure that the variables come from the model and not stored in the viewModel as they currently are. Since they are not even close to the final version (just a copy of the old one to use as a skeleton) I'll approve it.

2024-11-29 09:31 UTC, matvitn commented on app/src/main/java/com/android/shelfLife/viewmodel/ListFoodItemsViewModel.kt
> +open class ListFoodItemsViewModel(private val repository: FoodItemRepository) : ViewModel() {
Same comment as HouseHoldViewModel

2024-11-29 09:41 UTC, ricardo-perello commented on app/src/main/java/com/android/shelfLife/model/newhousehold/HouseHoldRepositoryFirestore.kt
> +      val currentHouseholds = _households.value.toMutableList()
Thank you for pointing this out! The reason I convert _households.value to a MutableList is that _households is a StateFlow that holds an immutable list (List<HouseHold>), ensuring thread safety and preventing unintended modifications.

When updating the local cache, I need a temporary mutable copy to perform operations like adding or removing elements. Once the changes are made, I reassign the updated list back to _households.value to maintain its immutability for consumers.

If there’s a better way to manage this, like leveraging a more appropriate type or structure, I’m open to suggestions! My goal was to ensure immutability at the exposed StateFlow level while keeping the internal update logic straightforward. Let me know if you think a different approach would work better! 😊

2024-11-29 10:00 UTC, ricardo-perello commented on app/src/main/java/com/android/shelfLife/model/newFoodItem/FoodItem.kt
> +  UNOPENED,
in a group vote we decided to keep unopened

2024-11-29 10:02 UTC, ricardo-perello commented on app/src/main/java/com/android/shelfLife/model/newFoodItem/FoodItemRepositoryFirestore.kt
> +      val currentFoodItems = _foodItems.value.filterNot { it.uid == foodItemId }
we looked at the function we talked about and its also O(n) so in the end im not going to change.

2024-11-29 10:06 UTC, matvitn approved these changes
Thanks for addressing my concerns!!!! If everything is good with the others then I have no issues. The justification for the unmutable list and the other methods also make sense to me so this PR is officially approved!

2024-11-29 10:06 UTC, merged