Integrate Camera and Add Navigation from Sign-In Screen
commit-crimes/shelf-life pull request #24
Opened 2024-10-04 17:19 UTC by ricardo-perello

## Description:

This pull request integrates the camera functionality and adds navigation from the Google sign-in screen to the barcode scanner screen.

## Key Changes:

1. **Camera Integration**:
   - Implemented CameraX for live camera preview functionality in the `BarcodeScannerScreen`.
   - Handled camera permissions to ensure proper initialization when users reach the camera screen.
   - Created a `BarcodeScannerScreen` that initializes and displays the camera preview.
   
2. **Navigation Integration**:
   - Added navigation logic to transition from the Google sign-in screen to the barcode scanner screen after successful sign-in.
   - Refactored the app structure to streamline navigation between authentication and the camera view.
   - Updated `MainActivity` to use `NavHost` for managing screen transitions.

## Changes in Files:

- Refactored `MainActivity` to focus on navigation.
- Created the `BarcodeScannerScreen` for displaying the camera preview.
- Updated `ShelfLifeApp` to manage transitions between the sign-in screen and the barcode scanner.

## Testing:

- Verified that the navigation from the sign-in screen to the barcode scanner screen works as expected.
- Checked that the camera permissions are requested and the camera preview is correctly displayed after authentication.

## Related Issues:

- None

2024-10-04 17:46 UTC, ElMaestroZ requested changes
Pop-up for requesting camera permission is missing and instead of displaying a black screen the user should be informed that the camera permission is not given.

2024-10-07 11:52 UTC, ricardo-perello commented
## Description:

This pull request adds full integration of camera functionality with permission handling and navigation, starting from Google sign-in to barcode scanning, along with a permission-denied flow.

## Key Changes:

1. **Camera Permission Handling**:
   - Implemented `CameraPermissionHandler` to request camera permissions and navigate users based on their response.
   - Added logic to handle permission denial by displaying the `PermissionDeniedScreen` with an option to guide users to grant permission in app settings.

2. **Camera Integration**:
   - Integrated CameraX for live camera preview functionality in the `BarcodeScannerScreen`.
   - Created the `BarcodeScannerScreen` to initialize and display the camera preview when permission is granted.

3. **Navigation Integration**:
   - Updated the navigation flow to transition from the Google sign-in screen to the camera permission handler, and from there to the barcode scanner or permission denied screen.
   - Refactored `MainActivity` to use `NavHost` for screen transitions between sign-in, permission handling, barcode scanning, and permission denied.

## Changes in Files:

- **MainActivity**: Refactored to handle navigation using `NavHost` for sign-in, camera permissions, and barcode scanning.
- **CameraPermissionHandler**: Added to manage camera permission requests and navigation based on permission state.
- **BarcodeScannerScreen**: Created to display the camera preview using CameraX.
- **PermissionDeniedScreen**: Added to guide users to enable camera permissions if denied.

## Testing:

- Verified the flow from the Google sign-in screen to the permission handler and barcode scanner.
- Tested the handling of camera permissions and the display of the appropriate screens (scanner or permission denied).
- Checked that the camera preview works correctly when permission is granted.

2024-10-07 12:37 UTC, ElMaestroZ approved these changes

2024-10-07 12:37 UTC, ElMaestroZ commented
Works perfectly.

2024-10-07 12:37 UTC, merged